# Generated by Django 4.2.7 on 2023-11-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='name_inspect_1',
            field=models.CharField(default='hola', max_length=50),
        ),
        migrations.AddField(
            model_name='inventory',
            name='name_inspect_2',
            field=models.CharField(default='hola2', max_length=50),
        ),
    ]
