# Generated by Django 4.2.7 on 2023-11-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_name_inspect_1_inventory_name_inspect_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name_inspect_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name_inspect_2',
            field=models.CharField(max_length=50),
        ),
    ]
